on:
  push:
    branches:
      - main
jobs:
  build-backend:
    defaults:
      run:
        working-directory: backend
    name: Build the application
    runs-on: ubuntu-22.04
    concurrency:
      cancel-in-progress: true
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4 # ratchet:actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v3 # ratchet:actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Run gradle build
        run: ./gradlew build --no-daemon
      - uses: docker/docker/setup-buildx-action@v3 # ratchet:docker/setup-buildx-action@v3
      - uses: docker/docker/build-push-action@v5 # ratchet:docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
